### ISSUE TITLE
Missing package: wxPython

### ISSUE THREAD

**Issue by bennuttall** [piwheels/packages#1]
Missing package
Package name: `wxPython`
Link to PyPI page: https://pypi.org/project/wxPython
Link to piwheels page: https://www.piwheels.org/project/wxPython
Version: all

The project's [wiki](https://wiki.wxpython.org/BuildWxPythonOnRaspberryPi) states these as build dependencies:

```
build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev
```

https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html

**Comment by waveform80** [comment]
Since I've re-enabled wxPython we've now got *some* successful builds. However, the latest 4.1.1 build failed on buster (cp37m). I've had a quick skim of the build output and it looks like a genuine failure (not out of disk space or anything like that); some incompatibility of the wxPython code and the Pi's /opt/vc gl libs. If anyone's interested in digging further into this, feel free to leave a comment and I'll pastebin the build log somewhere but for now I'd consider this "resolved" (given we've got at least some successful builds on both ABIs).
