### ISSUE TITLE
Missing package: igtool

### ISSUE THREAD

**Issue by JustAHackers** [piwheels/packages#105]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.7 or all
I am the maintainer: Yes/No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```

**Comment by bennuttall** [comment]
It seems you have registered both `igtool` and `igtools`, uploaded several releases, then deleted them, then complained that they're "missing" from piwheels without any explanation. Both times the packages weren't missing, they just had your deleted packages left behind.

This is not the way to use PyPI. You need to do more testing locally before releasing to PyPI, or deal with the fact that your old versions are still available, like all other packages. And why register multiple names?

I'm inclined not to fix these issues because you're abusing the system, making demands, not filling out the templates and not being helpful when asking others to do work for you.
