### ISSUE TITLE
Missing package: vtk

### ISSUE THREAD

**Issue by katealhola** [piwheels/packages#121]
Package name: vtk
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/vtk/
Link to piwheels page: https://www.piwheels.org/project/vtk/
Version: all
Python version: all
I am the maintainer: No
More information:

package missing, build fail on page 

```bash
kate@rt-raspi:~/qtpyvcp $ sudo pip3 install vtk
[sudo] password for kate: 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vtk
  Could not find a version that satisfies the requirement vtk (from versions: )
No matching distribution found for vtk
kate@rt-raspi:~/qtpyvcp $ sudo pip install vtk
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vtk
  Could not find a version that satisfies the requirement vtk (from versions: )
No matching distribution found for vtk

```

```python
print("code here")
```

**Comment by bennuttall** [comment]
There's no source distribution for the latest version of this package on PyPI: https://pypi.org/project/vtk/#files

This means there's nothing for us to build. You'll have to take this up with the package maintainers.

It looks like the others failed to build but only because they were missing source distribution at the time. I've deleted the builds so they will be re-attempted. Watch the project page for updates.

**Comment by bennuttall** [comment]
Oh, I didn't realise - but they're all binary only - no source distribution for any versions. You'll have to ask the maintainers to provide a source distribution.
