### ISSUE TITLE
panda3d

### ISSUE THREAD

**Issue by markspilot** [piwheels/packages#124]
Package name: panda3d
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/Panda3D/
Link to piwheels page: N/A
Version: all
Python version: 3.7 
I am the maintainer: No
More information:

Please use code blocks where appropriate:

python3 -m pip install panda3d

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
  Collecting panda3d
  Could not find a version that satisfies the requirement panda3d (from versions: )
  No matching distribution found for panda3d

**Comment by bennuttall** [comment]
If you look at [PyPI](https://pypi.org/project/Panda3D/#files) you'll see that there's no source distribution, only wheels (for other platforms) so there's nothing for us to build.

You'll have to take it up with the package maintainers, and ask them to provide a source distribution.

**Comment by markspilot** [comment]
Ok thanks, I'm really new to this is there any way I can install panda3d on
my raspberry pi?

**Comment by bennuttall** [comment]
You need to ask panda3d that.

Try looking at their website: https://www.panda3d.org/

[This page](https://www.panda3d.org/download/sdk-1-10-6/) says you can build from source: https://www.panda3d.org/download/panda3d-1.10.6/panda3d-1.10.6.tar.gz

Or get it from GitHub: https://github.com/panda3d/panda3d

Please open a github issue [here](https://github.com/panda3d/panda3d/issues/new) and ask them to upload a source distribution to PyPI so that you can use it on Raspberry Pi.

**Comment by markspilot** [comment]
Thanks your a star!
