### ISSUE TITLE
Missing web3 package

### ISSUE THREAD

**Issue by n3me5is-git** [piwheels/packages#141]
Package name: web3
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/web3/
Link to piwheels page: https://www.piwheels.org/simple/web3/
I am the maintainer: No
More information:

On a Raspberry 4 I'm using python 3.7 with raspbian and using `pip3 install web3'. The error I get is
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting web3
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/web3/
```
All the other packages I need are installing fine.

The web3 package is important especially for blockchain projects. It should be available

**Comment by bennuttall** [comment]
It looks like it's been wrongly deleted. We recently added support for honouring deletions from PyPI and the logic is somewhat complex (due to projects being deleted and recreated).

```
Aug 10 22:49:47 piwheels piw-master[32549]: master.cloud_gazer: marking package web3 for deletion
Aug 10 22:49:50 piwheels piw-master[32549]: master.the_scribe: deleting package web3
```

It was indeed deleted on 10 August, but it shouldn't have been, as the currently live package has been up since 2016.

**Comment by waveform80** [comment]
Okay, figured this one out and it's my fault: the current regex for identifying deletions in PyPI has always been wrong but it hasn't mattered much previously because it just marked stuff without actually deleting it. The regex is:

```
^remove(?: (?:package|release))?
```

Which is meant to match the historic `"remove"` action which PyPI used (with version set to None to indicate package removal), or `"remove package"` (which is actually wrong and should be "remove project" - doh) or `"remove release"` which are the modern actions. There are also actions like `"remove Owner foo"` and `"remove url http://foo.org"` which we ought to ignore.

See the error? I'll give you a hint: one missing char on the end :)

Anyway, I'll get this patched up in a mo and take a run thru my offline copy of the events to figure out how things "should" be. We can regenerate the necessary rows in packages/versions from there and let it re-build its way through them.
