### ISSUE TITLE
Error:404 file not found - https://www.piwheels.org/simple/pkg-resources/

### ISSUE THREAD

**Issue by KermenTheFrog** [piwheels/packages#153]
Hi i need to use this for a project that i'm doing 
i'm getting an couldn't install packages due to an environment error 404 client error
so from what i can tell the package has been removed from the website at some point.

**Comment by cl3m3nt** [comment]
Hello, 

same here on Raspberry Pi 4 buster where I got:
_Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pkg-resources/_

I hit this problem after trying to create a new virtualenv.
Virtualenv install is successful: 
_sudo apt install virtualenv python3-virtualenv -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-virtualenv is already the newest version (15.1.0+ds-2).
virtualenv is already the newest version (15.1.0+ds-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded._

**Comment by bennuttall** [comment]
It's fixed now. We just deleted all packages which had no versions associated with them, which we thought would be safe.

Oddly, pkg-resources doesn't exist on PyPI: https://pypi.org/project/pkg-resources/

But it does have a simple index (which is empty): https://pypi.org/simple/pkg-resources/

And it gets a lot of hits somehow. Looks like venv depends on it ... but the only way to get it is from your system python - not with pip.

@di can you shed any light? Is this a one-off?

**Comment by waveform80** [comment]
/me makes a mental note that whenever I utter the words "yeah, that should be fine" one should assume the world is about to break ... again

**Comment by di** [comment]
Comes from here: https://github.com/pypa/pkg_resources

Vendored into setuptools here: https://github.com/pypa/setuptools/tree/master/pkg_resources

**Comment by bennuttall** [comment]
@di any idea why it doesn't have a project page or json but does have a simple index and does appear in xmlrpc `list_packages()`?

**Comment by di** [comment]
It's being squatted:

![image](https://user-images.githubusercontent.com/294415/92524963-9d2e8600-f1e8-11ea-9b94-37bdb409cc96.png)

I should probably just move it to the blocklist instead.
