### ISSUE TITLE
python-lightblue

### ISSUE THREAD

**Issue by subhajitsarkar91** [piwheels/packages#214]
Package name: example
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: e.g. 3.5 or all
I am the maintainer: No
More information:

Please use code blocks where appropriate:

```bash
command line commands here
```

```python
print("code here")
```services = lightblue.findservices(target_address)  
for service in services:  
     if service[2] == "OBEX Object Push":  
          obex_port = service[1]       
          print ("OK, service '", service[2], "' is in port", service[1], "!" ) 
          break

**Comment by bennuttall** [comment]
It looks like you are looking for support with a particular package, but you're asking for help in the wrong place. This is a Raspberry Pi package building service, so if your issue is with the library, please find the right place for support.

If you do in fact have an issue specifically relating to this package's distribution on piwheels, please fill out the issue template properly explaining your issue clearly.
