### ISSUE TITLE
Illegal instruction when: from PIL import Image

### ISSUE THREAD

**Issue by darton** [piwheels/packages#269]
### Package name

Pillow

### Package version

9.0.0

### PyPI URL

https://pypi.org/project/Pillow/

### piwheels URL

https://www.piwheels.org/project/pillow/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [X] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

Importing Image or ImageDraw from Pillow results in "Illegal instruction" error

Platform: Raspbery Pi Zero W
OS: Raspbian GNU/Linux 11 (bullseye)
Python: Python 3.9.2 (default, Mar 12 2021, 04:06:34)
Pillow: 9.0.0

from PIL import Image
or
from PIL import ImageDraw

result:

Illegal instruction

**Comment by Sebwap** [comment]
Same issue with others packages such as psutil, beautifulsoup4.

**Comment by michaeltoohig** [comment]
I have this issue with numpy and scipy as well.

For context, I can not get a fast internet connection and using `pip install` on the pi always results in a timeout error for packages over several MB. Doesn't matter if I set timeout for 60 minutes the timeout is always about 10 minutes so the issue is on server side / my side due to slow internet (around 10 kb/s). However, I am having success downloading the files with wget and wget handles reconnecting after the timeout and completes the download. Then, I use `--find-links` to point to a directory containing the `whl` files and after the installation I have the `Illegal Instruction` error when I import the package. I had thought the issue was because I was downloading the files outside of pip but given others have the same issue it may not be my unorthodox installation process.

**Comment by bennuttall** [comment]
It looks like this issue is present in all cp39 wheels built in the last few weeks. Something must have changed in gcc or something which is producing armv6l-incompatible wheels. We're looking into it. For now, try the previous version of a package, or use `--no-binary :all:`.

**Comment by loiccoyle** [comment]
I'm getting this for `numpy>=1.21.5`

To reproduce:
```sh
pip install numpy
python -c import numpy
```

Related issue: 
https://github.com/numpy/numpy/issues/20765

**Comment by MichaIng** [comment]
Same recognised here with `psutil` on `armv6l` RPi models, hence RPi 1 and Zero (1). Probably something on the CI/CD pipeline changed so that `armv6l` compatibility was lost, respectively an ARMv7-only build flag used somehow?

**Comment by bennuttall** [comment]
This issue has been identified and we hope to fix asap. Follow in #276

**Comment by bennuttall** [comment]
The wheels have been rebuilt and this issue should now be resolved

**Comment by Sebwap** [comment]
Yes it's ok now.
Thx everyone !
