### ISSUE TITLE
Missing package: opencv-contrib-python

### ISSUE THREAD

**Issue by parviza9999** [piwheels/packages#288]
### Package name

opencv-contrib-python

### Package version

4.1.0.25

### PyPI URL

https://pypi.org/project/opencv-contrib-python/

### piwheels URL

https://www.piwheels.org/project/opencv-contrib-python/

### Python version

- [ ] Python 3.5
- [ ] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

**Comment by bennuttall** [comment]
Looks like it ran out of memory - I'll try and build offline

**Comment by bennuttall** [comment]
I've built the latest two versions, and they're now available.

But I've just noticed you asked for a much older version, which came out 3 years ago. We have builds for that version for Stretch and Buster but not Bullseye because Bullseye wasn't out then. It's not available because there's no sdist on PyPI and we built it from GitHub sources but we're not doing that retrospectively old releases for a new OS.

Please use one of the new versions which is now available.

**Comment by parviza9999** [comment]
Does TF still work on pi 4 with latest OS? I'm trying to run a python code
that detects facial emotions using prebuilt model that requires pip install
tensor flow and running into error.

**Comment by bennuttall** [comment]
The versions of TF we have wheels for work on the Pi 4, but we don't have any 2.x versions as Google don't release them for Pi any more.

**Comment by themarpe** [comment]
Hi @bennuttall 

Latest two versions `4.6.0.66` and `4.5.5.64` seem to also fail building, with out of memory error.

Have you perhaps considered utilizing some sort of swap to just slightly increase the memory availability for builds? This seems to be a recurring issue and as soon as project uses a tad more complex bindings it hits such requirements.
