### ISSUE TITLE
Missing package: casadi-kin-dyn

### ISSUE THREAD

**Issue by Tiantiansayhi** [piwheels/packages#311]
### Package name

casadi-kin-dyn

### Package version

1.2.0

### PyPI URL

https://pypi.org/project/casadi-kin-dyn/

### piwheels URL

https://www.piwheels.org/project/casadi-kin-dyn/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [X] Yes

### More information

When I pip install this package, i found the error as follows:
ERROR: Could not find a version that satisfies the requirement casadi-kin-dyn (from versions: none)
ERROR: No matching distribution found for casadi-kin-dyn
and i use python 3.7 and ubuntu 18.04 , so why it cannot be installed successfully?

**Comment by bennuttall** [comment]
Are you using a Raspberry Pi? piwheels is a service for Raspberry Pi users.

If you're using Raspberry Pi, you can't install it because there's no source distribution for us to build. Also we don't support Ubuntu.

If you're not using Raspberry Pi, a) you're reporting this issue in the wrong place and b) this package only provides wheels for 64-bit Linux (for PCs, not Raspberry Pi) for Python 3.6 and 3.8: https://pypi.org/project/casadi-kin-dyn/#files
