### ISSUE TITLE
Missing package: cmake 3.23.3 on python 3.7

### ISSUE THREAD

**Issue by JanLahmann** [piwheels/packages#316]
### Package name

cmake

### Package version

3.23.3

### PyPI URL

https://pypi.org/project/cmake/

### piwheels URL

https://www.piwheels.org/project/cmake/

### Python version

- [ ] Python 3.5
- [X] Python 3.7
- [ ] Python 3.9

### I am the maintainer

- [ ] Yes

### More information

make 3.32.3 is listed as available for python 3.7 on https://www.piwheels.org/project/cmake/, 
but actually the whl file is missing at https://www.piwheels.org/simple/cmake/ (and is just available for python 3.9)

**Comment by bennuttall** [comment]
Sorry you were looking at a broken template. Since we removed the cp35m column the table got messed up.

Updated now: https://www.piwheels.org/project/cmake/

The cp37m build failed and the cp39 build succeeded. You can click the icons to view the build log and see why it failed here: https://www.piwheels.org/logs/0000/0857/2572.txt

If you can see how this might be fixed, please let us know.

**Comment by bennuttall** [comment]
Newer versions are built now :+1:
