### ISSUE TITLE
Missing package: black

### ISSUE THREAD

**Issue by jimmyharris** [piwheels/packages#79]
Package name: black
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/black/
Link to piwheels page: https://www.piwheels.org/project/black/
Version: all
Python version: e.g. 3.7
I am the maintainer: No
More information:

attempting to install black via `pipx`

```bash
$ pipx install black
  installed package black 0.0, Python 3.7.3
  These apps are now globally available
    - black
done! ✨ 🌟
```

Running black yields the following result:

```bash
 $ black --version
Traceback (most recent call last):
  File "/home/pi/.local/bin/black", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/pipx/venvs/black/lib/python3.7/site-packages/black.py", line 5, in main
    raise NotImplementedError("This is still being implemented.")
```

The expected result is:
```bash
$ pipx install black
  installed package black 19.10b0, Python 3.7.3
  These apps are now globally available
    - black
    - blackd
```
and running `black --version should yield:
```bash
$ black --version
black, version 19.10b0
```

**Comment by bennuttall** [comment]
Thanks for the report (and for filling out the template).

Oh, that's odd. black on PyPI only hosts sdist and a Python 3.6 wheel. Somehow we're picking that up instead of building it ourselves. I think we have `--no-binary` added to the wheel command in a branch that's not merged/deployed yet, which should fix this. I'll have a look later.

**Comment by bennuttall** [comment]
Ok, just realised what's going on. Two things:

1. You're installing the "latest release" which is actually version `0.0` - there are many alpha/beta releases since then but `pip install black` will ignore any pre-release versions like `19.10b0`. If you want the latest version regardless of release status, you need to add `--pre`.

2. The `py36` python tag is actually just a minimum, not a match, so that'll work on Python 3.7.
